version: "2"

services:
  # The Application
  app:
    container_name: twill-laravel-container 
    working_dir: /var/www
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  
  #The Web Server
  web: 
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www 
    volumes:
      - ./:/var/www   
    ports:
      - 80:80
     

  #The Database
  database:
    image: mysql:5.7.24
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=twill-app"
      - "MYSQL_USER=root" 
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"

volumes:
  dbdata:
